### DISCUSSION TITLE
Credentials for aws s3 objects source

### DISCUSSION THREAD

**Discussion by btheu** [MaterializeInc/materialize#5891] [Q&A]
Hi, 

While trying to use s3 objects source i got following error:

`WARN dataflow::source::s3: unable to list bucket mybucket1: Couldn't find AWS credentials in environment, credentials file, or IAM role. (1 retries remaining)`

Current `/root/.aws/credentials` content is as follow (after secret substitution):

```
[default]
role_arn=arn:aws:iam::<id>:role/<rolename>
role_session_name=materialize
source_profile=staging

[staging]
aws_access_key_id=<secret>
aws_secret_access_key=<secret>
```
As validation, `aws s3 ls` command is successful on AWS CLI2 with this credentials file.

What should looks like credentials file for using s3 objects source from Materialize ?

regards,

**Comment by quodlibetor** [comment]
That looks reasonable and should be picked up. To double check, is `materialized` running as root?

**Reply by quodlibetor** [reply]
Also are you running on the host or in docker? And if you are running in docker are you maybelline that file in the docker container?

**Reply by btheu** [reply]
Hi,

This is running inside docker container, here the docker compose service definition:

```
  materialize:
    image: materialize/materialized:v0.7.0
    container_name: materialize
    ports:
      - 6875:6875
    volumes:
      - $PWD/aws-credentials:/root/.aws/credentials
    command: --experimental
```

This should be running inside as root, isn't it ?
