### ISSUE TITLE
clusters with no AZ constraint are pinned to a specific availability zone

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#20659]
### What version of Materialize are you using?

v0.61.0

### What is the issue?

The system clusters are pinned to a specific availability zone, which reduces K8s options when one needs to reschedule them. I suspect the same also applies to user-defined clusters without an explicit AVAILABILITY ZONE setting.

Such clusters should be free to move around across availability zones.

```
kubectl describe pod/cluster-s1-replica-2-0
...
Node-Selectors:              materialize.cloud/availability-zone=2
                             materialize.cloud/disk=false
```

and 

```
Node-Selectors:              materialize.cloud/availability-zone=2
                             materialize.cloud/disk=false
```

The other concerning thing is that they were both scheduled in the same availability zone. A round-robin algorithm would imply that the two would end up in two different availability zones.

**Comment by edude03** [comment]
Yeah if there isn't a reason not to, I suggest we don't use the `materialize.cloud/availability-zone=2` nodeSelector but instead use [Pod AntiAffinity ](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) so the pods can roam, and not be scheduled in the same AZ if possible

**Comment by teskje** [comment]
Paging @umanwizard because he worked on this way back when.

> The other concerning thing is that they were both scheduled in the same availability zone. A round-robin algorithm would imply that the two would end up in two different availability zones.

I think we are doing round-robin between replica's within the same cluster, not replica's of different clusters. Why do you find this concerning?

> use Pod AntiAffinity so the pods can roam, and not be scheduled in the same AZ if possible

Doesn't anti-affinity hard forbid scheduling of pods if the affinity rules can't be followed? That would mean that we could never have more replicas than there are AZs.

**Comment by benesch** [comment]
> > use Pod AntiAffinity so the pods can roam, and not be scheduled in the same AZ if possible
> 
> Doesn't anti-affinity hard forbid scheduling of pods if the affinity rules can't be followed? That would mean that we could never have more replicas than there are AZs.

Exactly! We should be using [pod topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/). That lets you express the constraint of "balance the replicas across AZs as evenly as possible."

I think it's a very simple fix. Thanks to @pH14, we wrote down `az_user_specified: false` whenever we selected an AZ at random for a replica. We should migrate all replicas that don't have an user-specified AZ to use topology spread constraints, instead of pinning to the AZ we selected at random.

**Comment by benesch** [comment]
@guswynn might pick this up as part of the upsert spill to disk work. The i4i instance types we're using are particularly unavailable, which makes it all the more important to allow disk-enabled cluster replicas to float between AZs.

**Comment by philip-stoev** [comment]
> whenever we selected an AZ at random for a replica

Speaking of randomness, both system clusters are pinned to the **same** zone right now, so it is not even random. Unless that code is to be replaced in its entirety, it is something worth looking at:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize-bisect/test/cloudtest$ kubectl describe pod/cluster-s1-replica-2-0 | grep avail
Node-Selectors:              materialize.cloud/availability-zone=3
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize-bisect/test/cloudtest$ kubectl describe pod/cluster-s2-replica-3-0 | grep avail
Node-Selectors:              materialize.cloud/availability-zone=3
```

I ran the experiment 5 times, with identical outcomes.

**Comment by philip-stoev** [comment]
Also see existing cloudtest:

````
pytest.mark.skip(reason="Not currently guaranteed by implementation.")
def test_create_clusters_antiaffinity(mz: MaterializeApplication) -> None:
    """Test that multiple independent clusters are spread out to different availability zones."""
```

**Comment by philip-stoev** [comment]
See also https://github.com/MaterializeInc/materialize/issues/14170

**Comment by alex-hunt-materialize** [comment]
Notes from topology discussion in today's cloud hangout:

- Require all replicas to specify AZ or not specify AZ. No mixing specified and unspecified.
- Do not automatically choose an AZ for them if they do not specify an AZ.
- If the user explicitly asks for AZs, then put that in the NodeAffinity or NodeSelector (hard constraint).
- Always include a hard anti-affinity for other replicas in the same cluster to avoid the same node.
- Add a soft topology spread constraint to try to put replicas in the same cluster in different AZ. If not satisfiable, schedule anyway to the same AZ.
- Open questions about how this interacts with karpenter, we suspect it will just schedule anyway and not spawn a new node.

**Comment by guswynn** [comment]
discussion continued here: https://materializeinc.slack.com/archives/CL68GT3AT/p1690231637973819

**Comment by benesch** [comment]
Here is a pseudo-design doc that charts a path to automatic balancing for
non-horizontally scaled replicas.

## Background

Our production nodes have the following relevant labels:

Name | Meaning | Example
-----|---------|--------
`kubernetes.io/hostname` | Node hostname | ip-10-2-29-180.ec2.internal
`topology.kubernetes.io/region` | Cloud provider region | `us-east-1`
`topology.kubernetes.io/zone` | Availability zone | `us-east-1a`

## Goals

* Managed clusters
  * Replicas are best-effort spread across user-specified allowable zones for
    the cluster. If no user-specified allowable zones, all zones are allowable.
  * If the replication factor is not a multiple of the number of allowable
    zones, replicas are spread as evenly as possible (i.e., a maximum skew
    of one in the number of replicas per zone).

* Unmanaged clusters
  * A replica with user-specified allowable zones is always scheduled to one of
    those zones. If no user-specified allowable zones, all zones are allowable.
  * Replicas are best-effort spread across zones. No effort is made to define
    the spread semantics when different replicas of the same cluster have
    different allowable zones.

## Non-goals

* Handling automatic spreading for horizontally scaled (2xlarge+) replicas,
  since no customers are currently using replicas this large.

* Descheduling pods, a la the
  [descheduler](https://github.com/kubernetes-sigs/descheduler), is left to
  future work. See [dynamic cluster
  scheduling](https://github.com/MaterializeInc/materialize/issues/13870).

## Implementation

### SQL

We allow allow specifying multiple AZs when creating a cluster replica via `CREATE CLUSTER REPLICA ... AVAILABILITY ZONES`.

### Kubernetes orchestrator

We adjust the Kubernetes orchestrator to apply a pod specification with the following affinity/topology spread configuration:

```yml
  affinity:
    # The node affinity constrains pods to the user-specified allowable zones.
    # If the user does not specify allowable zones, no node affinity is
    # specified.
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values: "all user-specified AZs for this replica"
    # The pod anti-affinity ensures that multiple replicas of the same cluster
    # are never scheduled to the same node.
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions: "other pods of this cluster but NOT of this specific replica"
        topologyKey: kubernetes.io/hostname
    # Prefer to schedule multiple pods for the same replica in the same zone.
    # This handles the case where the user has created a horizontally scaled
    # replica (2xlarge+) but has not constrained the allowable zones--best to
    # schedule those
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions: "other pods of this specific replica"
          topologyKey: topology.kubernetes.io/zone
  # The topology spread constraint does best-effort spreading of pods across
  # zones.
  #
  # This does *not* work for horizontally scaled replicas (2xlarge+), and so
  # this constraint is *not* emitted for horizontally scaled replicas.
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchExpressions: "other pods of this cluster that are not part of a horizontally scaled replica"
```

## How we explain this

To maximize availability, we recommend:

  * For non-horizontally scaled replicas, use managed clusters with a
    replication factor of two and at least two allowable zones.

  * For horizontally scaled replicas, we recommend using unmanaged clusters with
    two replicas, each pinned to a single zone, and not pinned to the smae zone.
    We warn that this has the defect of not being able to handle two concurrent
    zone failures.
