### ISSUE TITLE
durably store Kafka offsets to resume without consuming/producing duplicate messages

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2225]
Because it's not storing offset for Kafka Connector if consumer reconnects it starts processing the topic data from the beginning. 

I'm using default configuration from the docker file. 

Here's my docker-compose file

```
version: '3.7'
services:
    materialized:
        image: materialize/materialized:latest
        ports:
            - 6875:6875
    mzcli:
        image: materialize/mzcli
        links:
            - materialized
```
