### ISSUE TITLE
dbt: `cluster` connection key ignored in `profiles.yml`

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#22875]
### What version of Materialize are you using?

d330e30bd65db7340d1befb83c47eb8467343332

### What is the issue?

The `cluster` setting in `profiles.yml` is ignored altogether. The default cluster appears to be used:

My config looks like this:

```
    prod:
      type: materialize
      threads: 1
      host: "{{ env_var('MATERIALIZE_PROD_SANDBOX_HOSTNAME') }}"
      port: 6875
      user: "{{ env_var('MATERIALIZE_PROD_SANDBOX_USERNAME') }}"
      password: "{{env_var('MATERIALIZE_PROD_SANDBOX_APP_PASSWORD')}}"
      dbname: qa_canary_environment
      schema: public
      autocommit: True
      cluster: FOO
```

and I would expect all queries to fail with `unknown cluster FOO`. Instead, they all succeed.

The same setting in `dbt_project.yml` seems to **NOT** be ignored:

```
tests:
   +cluster: 'BAR'
```

results in an expected error about bar not existing.
