### ISSUE TITLE
Negative result for count(*)

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2313]
```
mz> select count(*) from giav;
+---------+
| count   |
|---------|
| -18665  |
+---------+
SELECT
Time: 1.340s (a second), executed in: 1.322s (a second)
mz>
```

materialized v0.1.3-dev (9ce7a0fba58c9d881258c01cf682a6eac20e9d34)

**Comment by ruchirK** [comment]
Hi @bhoomit ! This definitely looks like a bug - thank you for reporting! Can you give me some more info on the state of the system at the time you triggered this bug?
e.g. 

1. is `giav` a source or a view? If it's a source is it a debezium source?
2. approximately how many rows did you expect to be in `giav`? tens? hundreds? millions?
3. Does it persistently give the same incorrect answer for `count(*)` or do the answers vary or does it eventually return the correct answer?

**Comment by bhoomit** [comment]
Hi @ruchirK thanks for the quick response :) 

1. `giav` is a view. Kafka, Avro, Debezium Envelop
2. I want at least 300 Million rows, but this happens as soon as I create the view. 
3. Yes, it persists. It does change but doesn't correct. 

(4.) Now its crashing after a while. And since I'm not able to see progress, I don't know when it crashes. 

FYI. I'm running this inside a docker. 2 CPUs. 14 GB RAM. 

```
CONTAINER ID        NAME                           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f931cdeb7887        bhoomitvasani_materialized_1   124.25%             3.317GiB / 15.22GiB   21.79%              3.84GB / 13.6MB     0B / 0B             47
```

docker-compose.yml
```
version: '3.7'
services:
  materialized:
    image: materialize/materialized:latest
    ports:
      - 6875:6875
    entrypoint:
      - materialized
      - --log-file=stderr
      # - --processes=2
      # - --threads=2
      - --batch-size=10000
  mzcli:
    image: materialize/mzcli
    links:
      - materialized
```
