### ISSUE TITLE
Doesn't recover existing materialized view "records" after restart/crash

### ISSUE THREAD

**Issue by bhoomit** [MaterializeInc/materialize#2323]
docker-compose.yml

2 CPUs, 15 GB RAM

```
version: '3.7'
services:
  materialized:
    image: materialize/materialized:latest
    ports:
      - 6875:6875
    volumes:
      - ./materialized/mzdata:/mzdata
      - ./materialized/logs:/logs/
    entrypoint:
      - materialized
      - --log-file=/logs/materialize.log
  mzcli:
    image: materialize/mzcli
    links:
      - materialized
```
