### ISSUE TITLE
Prometheus failed to start when running chbench

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4847]
Running the `ingest-postgres` benchmark, the Grafana panels failed to load data. The error message displayed was "Bad Gateway". Going directly to the Prometheus port in my browser showed that the Prometheus was not responding. Since the dashboard container runs multiple processes, the stdout of the container was not very helpful.

After running `docker exec` to gain access to the container, the supervisord log has the following contents:

```
2020-11-20 23:50:48,108 INFO supervisord started with pid 7
2020-11-20 23:50:49,112 INFO spawned: 'grafana' with pid 13
2020-11-20 23:50:49,117 INFO spawned: 'prometheus' with pid 14
2020-11-20 23:50:49,119 INFO spawned: 'sql_exporter' with pid 15
2020-11-20 23:50:49,193 INFO exited: prometheus (exit status 2; not expected)
2020-11-20 23:50:50,115 INFO success: grafana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-20 23:50:50,122 INFO success: sql_exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-20 23:50:50,197 INFO spawned: 'prometheus' with pid 62
2020-11-20 23:50:50,274 INFO exited: prometheus (exit status 2; not expected)
2020-11-20 23:50:53,123 INFO spawned: 'prometheus' with pid 99
2020-11-20 23:50:53,198 INFO exited: prometheus (exit status 2; not expected)
2020-11-20 23:50:56,205 INFO spawned: 'prometheus' with pid 125
2020-11-20 23:50:56,285 INFO exited: prometheus (exit status 2; not expected)
2020-11-20 23:50:57,287 INFO gave up: prometheus entered FATAL state, too many start retries too quickly
```

**Comment by cirego** [comment]
Oh, wait, I was wrong. It does appear that there is an error message in `stdout`:

```
prometheus > level=info ts=2020-11-20T23:50:49.187Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
prometheus > level=info ts=2020-11-20T23:50:49.187Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-16:51:47)"
prometheus > level=info ts=2020-11-20T23:50:49.187Z caller=main.go:339 host_details="(Linux 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 3892a0c4f015 (none))"
prometheus > level=info ts=2020-11-20T23:50:49.187Z caller=main.go:340 fd_limits="(soft=1048576, hard=1048576)"
prometheus > level=info ts=2020-11-20T23:50:49.187Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
prometheus > level=error ts=2020-11-20T23:50:49.187Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
grafana    > t=2020-11-20T23:50:49+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
prometheus > panic: Unable to create mmap-ed active query log
prometheus > 
prometheus > goroutine 1 [running]:
prometheus > github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe6a929d31, 0xb, 0x14, 0x2e940a0, 0xc000b88000, 0x2e940a0)
prometheus >    /app/promql/query_logger.go:117 +0x4cd
prometheus > main.main()
prometheus >    /app/cmd/prometheus/main.go:368 +0x4ed8
2020-11-20 23:50:49,193 INFO exited: prometheus (exit status 2; not expected)
```

**Comment by cirego** [comment]
I'm wondering if this has to do with some recent changes that I made to my docker configuration. I moved the `/var/lib/docker` directory from my boot-drive (m.2 PCIe SSD attached to motherboard) to an m.2 SSD mounted in a PCIe expander card. Both are NVMe devices, and both are `ext4`:

```
[chris-work:~] mount | grep /dev/nvme
/dev/nvme0n1p1 on / type ext4 (rw,relatime,errors=remount-ro)
/dev/nvme1n1p1 on /var/lib/docker type ext4 (rw,relatime,errors=remount-ro)
```

**Comment by cirego** [comment]
It appears that we are mounting a directory from the source checkout (`demo/chbench/prometheus/data`) as a volume in the container:

````
  # All monitoring
  dashboard:
    mzbuild: dashboard
    propagate-uid-gid: true
    environment:
      - 'MATERIALIZED_URL=materialized:6875'
    ports:
      - *grafana
      - *prometheus
    volumes:
      # ensure that data doesn't get lost across restarts
      - ./prometheus/data:/prometheus
      - grafana:/var/lib/grafana
      # specialized configurations
      # this load test customizes prometheus to scrape tpcch and peeker
      # and it adds a dashboard that customizes that information
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./grafana/conf/load-test.json:/etc/grafana/provisioning/dashboards/chbench-load-test.json
````
