### ISSUE TITLE
Run workflow steps do not inherit environment configuration from parents

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5588]
I have an example workflow that sets some environment variables:

```yaml
  ingest-bench-ci:
    env:
      MZ_WORKERS: 4
      CHBENCH_RUN_SECONDS: 60
      NUM_WAREHOUSES: 1
      OLTP_THREADS: 4
    steps:
      - step: workflow
        workflow: generate-snapshot
```

Via some intermediate steps, this calls `heavy-load-mysql`. However, it appears that variables are instead being populated from the environment:

```yaml
  heavy-load-mysql:
    steps:
    - step: run
      service: chbench
      daemon: true
      command: >-
        run
        --dsn=mysql --gen-dir=/var/lib/mysql-files
        --analytic-threads=0
        --transactional-threads=${OLTP_THREADS:-1}
        --run-seconds=${CHBENCH_RUN_SECONDS:-864000}
        -l /var/log/chbench.log
        --config-file-path=/etc/chbenchmark/mz-default-mysql.cfg
        --mz-url=postgresql://${MZ_HOST:-materialized}:6875/materialize?sslmode=disable
```

When I run `ingest-bench-ci`, `docker inspect` shows that `chbench` is running with
`--run-seconds=864000`:

```
            "Cmd": [
                "run",
                "--dsn=mysql",
                "--gen-dir=/var/lib/mysql-files",
                "--analytic-threads=0",
                "--transactional-threads=1",
                "--run-seconds=864000",
                "-l",
                "/var/log/chbench.log",
                "--config-file-path=/etc/chbenchmark/mz-default-mysql.cfg",
                "--mz-url=postgresql://materialized:6875/materialize?sslmode=disable"
            ],
```

Ideally, when running a workflow, we would propogate any environment variables downwards to
sub-workflows.

benesch or @quodlibetor, would love to hear you thoughts on this.

**Comment by cirego** [comment]
@benesch did you have thoughts on this?

I thought I had tagged you, but it appears I missed the `@`.

**Comment by cirego** [comment]
I have currently have this as a blocker for writing a CI job to verify the chbench ingest benchmark.

**Comment by benesch** [comment]
I'm afraid I don't have a good handle on how the environment variables in the `mzworkflows` block interacts with the environment variables in the rest of the Docker Compose file. Personally I find environment variables really hard to reason about: it's hard to find out where they've been set; it's easy to accidentally clear out the environment when forking child processes; they're not resilient to typos; etc.

In my ideal world we'd not use environment variables in mzcompose at all, except as hardcoded configuration parameters for containers where required. 

Roughly, I was thinking it'd be sweet if we allowed mzcompose workflows to define flags that could be plumbed around explicitly, like so:

```yml
  ingest-bench-ci:
    flags:
      - mz-workers: 4
      - chbench-run-seconds: 60
      - num-warehouses: 1
      - oltp-threads: 4
    steps:
      - step: workflow
        workflow: heavy-load-mysql
        flags:
          mz-workers: %{mz-workers}
          chbench-run-seconds: %{chbench-run-seconds}
          num-warehouses: %{num-warehouses}
          oltp-threads: %{oltp-threads}
  heavy-load-mysql:
    flags:
      - mz-workers
      - chbench-run-seconds
      - num-warehouses
      - oltp-threads
    steps:
    - step: run
      service: chbench
      daemon: true
      command: >-
        run
        --dsn=mysql --gen-dir=/var/lib/mysql-files
        --analytic-threads=0
        --transactional-threads=%{oltp-threads}
        --run-seconds=%{chbench-run-seconds}
        -l /var/log/chbench.log
        --config-file-path=/etc/chbenchmark/mz-default-mysql.cfg
        --mz-url=postgresql://%{mz-host}:6875/materialize?sslmode=disable
```
