### ISSUE TITLE
BI Demo error: mz_compose run demo-load error: missing field `sleep` for key `default_query` 

### ISSUE THREAD

**Issue by ruf-io** [MaterializeInc/materialize#5602]
### What version of Materialize are you using?

Ran into this error when trying to run the demo/chbench code after cloning the repo today, so I think that makes the version: `materialized v0.6.2-dev`

### How did you install Materialize?

* [ x] Docker image

### What was the issue?

Following instructions on the [Business Intelligence demo](https://materialize.com/docs/demos/business-intelligence/) on a bare Ubuntu 18.04 VM with  16 GB Memory / 8 CPU.

After running

```
./mzcompose run demo-load
```

Everything loads correctly until it exits with the error:

```
Unable to parse config file /etc/peeker/materialized-sources.toml: missing field `sleep` for key `default_query` at line 508 column 1
Failed! giving up: peeker --only-initialize -c /etc/peeker/materialized-sources.toml -q loadtest
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Reproduced across multiple machines and runs.

**Comment by cirego** [comment]
This regressed due to 76228ce4ae92b4d50977c13f4fd384da5b67cb5a changing how our serdes handle the sleep parameter. Should be quick to fix this up.

**Comment by cirego** [comment]
I'm not sure what's going on here -- but the file `/etc/peeker/materialized-sources.toml` does not exist within the docker container... and the only things that reference it are this document and the `demo-load` workflow:

```
[chris-work:~/materialize/materialize:(fix-5602[|]*)] rg sources.toml
demo/chbench/mzcompose.yml
346:        -c /etc/peeker/materialized-sources.toml

doc/developer/metabase-demo.md
50:      -c /etc/peeker/materialized-sources.toml \
```

**Comment by cirego** [comment]
It appears that this has been broken since 7f9515c056bfd69184b52db772d44d50aafe10ad. There used to be a function called `demo_init.sh` that was removed in this commit:

```
-peeker_demo_init() {
-    runv sed -e 's/materialized.*false/materialized = true/' ../../src/peeker/config.toml \
-        > peeker-config/materialized-sources.toml
-    dc_run peeker --only-initialize -c /etc/peeker/materialized-sources.toml -q loadtest
-}
``

**Comment by cirego** [comment]
It looks like we're running into this error because the base image has not been updated in a long time, and it still has an old copy of `materialized-sources.toml`:

```toml
[default_query]                
# the amount of time to sleep between peeks              
sleep_ms = 0                                                                                                           
# Spin up this many threads querying this view                                                                         
# This affects the ratio of times this query is executed vs other queries
thread_count = 1 
```

For reference it's supposed to look like this:

```toml
[default_query]
# Spin up this many threads querying this view 
# This affects the ratio of times this query is executed vs other queries
thread_count = 1
            
[default_query.sleep]
secs = 0
nanos = 0
```

**Comment by cirego** [comment]
It also appears that `demo-load` should really just be `demo`:

```yaml
  # Temporary migration workflow in case folks look at the docs before the next version
  # has been released
  demo-load:
    steps:
    - step: workflow
      workflow: demo
```
