### ISSUE TITLE
Improve Kafka integration testing

### ISSUE THREAD

**Issue by elindsey** [MaterializeInc/materialize#5968]
Current gaps:
1. Our kafka test suites don't run against older versions. Last week we had a create sink regression in a fairly recent version of kafka (https://github.com/MaterializeInc/materialize/commit/c583fe9b49b2bdc96cb9ad5090ea7634557c757f)
2. We don't have tests that exercise a Kafka config with multiple brokers
3. Due to point 2, we don't have tests that exercise multipartition sinks

These all touch on environment orchestration and will likely need mzcompose work. We do have some complex kafka tests today (such as this one for testing auth https://github.com/MaterializeInc/materialize/blob/main/test/kafka-ssl/mzcompose.yml), but nothing repeatable. It would be ideal if we could simply rerun all of our existing Kafka testdrive tests against a different Kafka version.

(There will be more issues when it comes to exactly once testing, but I'll list those separately when the initial tests are done)

**Comment by umanwizard** [comment]
@awang maybe a good thing for 0.9?

**Comment by elindsey** [comment]
Tagging @philip-stoev

**Comment by cirego** [comment]
This may not be the desired solution, so feel free to take it or leave it. I've had good luck writing wrapper scripts around `mzcompose` that use environment variables to run these kinds of matrix tests. However, on Monday @quodlibetor merged c2c060e665a2971e89c0c2dff441093017e2ed77, which should make it possible to do this via mzcompose. Something like the following should work for a parameterized test, assuming that the `test-kafka` workflow reads the `KAFKA_VERSION` environment variable as intended:

```
  all_kafka:
    - step: workflow
      workflow: run-with-kafka1
    - step: workflow
      workflow: run-with-kafka2

  kafka1:
    env:
      KAFKA_VERSION: 5.6.1
    - step: workflow
      workflow: test-kafka

  kafka1:
    env:
      KAFKA_VERSION: 6.5.0
    - step: workflow
      workflow: test-kafka
```
