### ISSUE TITLE
A tutorial instead of demos

### ISSUE THREAD

**Issue by set92** [MaterializeInc/materialize#6507]
I have been trying to replicate the chbench demo with another mysql database since the last thrusday, 6h per day, and I only know one thing, I'm dumb. So it would be cool to have a tutorial that goes step by step instead of a complete demo that the reader has to understand all the steps and know how all is connected.

In my case yesterday I want to connect debezium to a database and be able to use the views created by materialize to create a dashboard for business department and also use those view to know when a client has made a purchase. So finally I was able to not have any direct error, but now in the control center - Topics I don't have any movement at all. I tried using the CREATE SOURCE and CREATE VIEW to set it up avoiding the emptiness of control center.

```
CREATE SOURCE avro_pg_log
FROM KAFKA BROKER 'kafka:9092' TOPIC 'hostmysql.database.ps_log'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081';
```

```
CREATE VIEW view_pg_log
AS SELECT * FROM avro_pg_log;
```

But the contents of view_pg_log are not the actual data, is like the columns from kafka but not the real data.

```
materialize=> show columns from avro_pg_log;
    name     | nullable |  type  
-------------+----------+--------
 after       | t        | record
 before      | t        | record
 op          | f        | text
 source      | f        | record
 transaction | t        | record
 ts_ms       | t        | bigint
(6 rows)
```

I don't know where is the problem, I think that in debezium but not sure, and in that sense it would help having a tutorial of step by step knowing why or how is connected each part to the next.

Also in some hidden section you say the user has to be have permissions over all database?
```
CREATE USER debezium;
ALTER USER debezium IDENTIFIED WITH mysql_native_password BY 'debezium';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium';
GRANT ALL PRIVILEGES ON tpch.* TO 'debezium'@'%';
```
Or I could remove the last line? Because at the end materialize only reads no? So why the needs of ALL PRIVILEGES?

**Comment by ruf-io** [comment]
This is great feedback, thank you for the detailed write-up. We are working on more in-depth tutorials.

It sounds like the issue is in configuring Debezium to properly connect to MySQL and also translate changes from target tables to events.

1. Have you read through https://debezium.io/documentation/reference/tutorial.html#starting-mysql-database as a supplementary tutorial? It also uses docker images (which hides some complexity) but it might be helpful.
2. Once the debezium "connect" service is running, what is the `curl` request you send it to specify which db tables to monitor? (See https://debezium.io/documentation/reference/tutorial.html#registering-connector-monitor-inventory-database) _you may need to redact sensitive creds_

**Comment by set92** [comment]
1. I readed through debezium documentation and I did their tutorial, but I was not sure about the privileges that the user needs, because in debezium they do `GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'user' IDENTIFIED BY 'password';` but I'm worry because in materialize it also gives privileges to all tables `GRANT ALL PRIVILEGES ON tpch.* TO 'debezium'@'%';`. This is needed?

2. To be honest I didn't do any curl request because I didnt't know how, I tried with `curl -H "Accept:application/json" localhost:8083/connectors/` from the debezium tutorial but it returns `curl: (7) Failed to connect to 127.0.0.1 port 8083: Connection refused`, I suppose is because I have to enter in some machine and wasn't sure. But in the control center - Topics it shows all the tables from the database, so I suppose somehow all tables are replicated?

At the end I think I was able to set it up, although I don't really understand why it works. My idea was that Materialize was going to create some materialize views by default, like some `SELECT *...` for all tables in a database.

Also I had problems restarting the demo and I ended up doing `./mzcompose down -v` to take it down all the time, because I was modifying the files but didn't know how to update the image of the connector, and seems there is some error with kafka? At least this error appears #5456

So basically what I did is create the next files:

**simple-mysql-connector/docker-entrypoint.sh** Here I'm not sure what it does the top section, at first I thought that the tables specified in topics were going to be the ones replicated or the ones that materialize was going to create materialize tables by default, then I saw that in control center - topics it appears all tables, so idk.
<details><summary>docker-entrypoint.sh</summary>

```
#!/usr/bin/env bash

# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

set -euo pipefail

wait-for-it --timeout=60 zookeeper:2181
wait-for-it --timeout=120 kafka:9092

topics=(
    hostname.database.ps_orders
    hostname.database.ps_attribute
    hostname.database.ps_connections
    hostname.database.ps_search_word
    hostname.database.ps_log
)

wait-for-it --timeout=120 connect:8083

echo "${topics[@]}" | xargs -n1 -P8 kafka-topics --bootstrap-server kafka:9092 --create --partitions 1 --replication-factor 1 --topic

curl -H 'Content-Type: application/json' connect:8083/connectors --data '{
  "name": "prestashop-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "hostname",
    "database.port": "3306",
    "database.user": "username",
    "database.password": "password",
    "database.server.id": "5401",
    "database.server.name": "quido_mysql",
    "database.history.kafka.bootstrap.servers": "kafka:9092",
    "database.history.kafka.topic": "schema-changes.ps_orders",
    "include.schema.changes": "true",
    "provide.transaction.metadata": "true",
    "time.precision.mode": "connect"
 }
}'
```
</details>

**simple-mysql-connector/Dockerfile** (this one I'm not sure if it needs all of this, I liked more the example from debezium demo but it doesn't have the wait-for-it command)
<details><summary>Dockerfile</summary>

```
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

FROM confluentinc/cp-enterprise-kafka:5.3.0

# https://github.com/confluentinc/cp-docker-images/issues/764
RUN sed -i s,https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.3.0/deb/5.3,https://packages.confluent.io/deb/5.3, /etc/apt/sources.list

RUN apt-get update && apt-get -qy install curl

RUN curl -fsSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /usr/local/bin/wait-for-it \
    && chmod +x /usr/local/bin/wait-for-it

COPY docker-entrypoint.sh /usr/local/bin

ENTRYPOINT ["docker-entrypoint.sh"]
```
</details>



**./mzcompose.yml**
<details><summary>mzcompose.yml</summary>

```
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.


# Map from host-port:internal port
#
# This mostly just shows all the ports that are available to the host system, if you want
# to change these you must restart the docker-compose cluster.
x-port-mappings:
  - &kafka-internal ${KAFKA_PORT:-9092:9092}
  - &kafka-external 9093:9093
  - &schema-registry ${SR_PORT:-8081:8081}
  - &materialized ${MZ_PORT:-6875:6875}
  - &mysql ${MYSQL_PORT:-3306:3306}
  - &postgres ${POSTGRES_PORT:-5432:5432}
  - &control-center ${CC_PORT:-9021:9021}
  - &grafana 3000:3000
  - &prometheus 9090:9090
  - &metabase 3030:3000

version: '3.7'
services:
  cli:
    mzbuild: cli
    init: true
    depends_on:
      - materialized
  materialized:
    mzbuild: materialized
    ports:
     - *materialized
    command:
      - --workers=${MZ_WORKERS:-1}
      # We want this to eventually count up to the size of the largest batch in
      # an arrangement. This number represents a tradeoff between proactive
      # merging (which takes time) and low latency.
      #
      # 1000 was chosen by fair dice roll.
      - --differential-idle-merge-effort=1000
      - --timely-progress-mode=${MZ_TIMELY_PROGRESS_MODE:-demand}
      - --disable-telemetry
    environment:
      # You can, for example, add `pgwire=trace` or change `info` to `debug` to
      # get more verbose logs.
      - MZ_LOG=pgwire=debug,info
      - MZ_DEV=1
  mysqlcli:
    image: debezium/example-mysql:1.4
    command: ["mysql", "--host=hostname", "--port=3306", "--user=username", "--password=password", "--database=database"]
    init: true

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper:/var/lib/zookeeper
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    ports:
      - *kafka-internal
      - *kafka-external
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_HOST:-kafka}:9093
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_LOG_CLEANUP_POLICY: "compact"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      # To avoid race condition with control-center
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      KAFKA_JMX_PORT: 9991
    volumes:
      - kafka:/var/lib/kafka/data
  connect:
    image: debezium/connect:1.4
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on: [kafka, schema-registry]
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    ports:
      - *schema-registry
    environment:
     - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081

    depends_on: [zookeeper, kafka]
  simple-mysql-connector:
    build: simple-mysql-connector
    depends_on: [connect]

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.3
    depends_on: [zookeeper, kafka, connect]
    ports:
      - *control-center
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_METRICS_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_CONNECT_CLUSTER: "http://connect:8083"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_DEPRECATED_VIEWS_ENABLE: "true"
  # Metabase
  # We need to ~manually add our `metabase-materialize-driver` to /plugins
  # for Metabase to automatically load Materialize as a connection option.
  metabase:
    image: materialize/metabase:v0.0.5
    depends_on: [materialized]
    ports:
      - *metabase

  # All monitoring
  dashboard:
    mzbuild: dashboard
    propagate-uid-gid: true
    environment:
      - 'MATERIALIZED_URL=materialized:6875'
    ports:
      - *grafana
      - *prometheus
    volumes:
      # ensure that data doesn't get lost across restarts
      # data will be lost if you remove docker volumes (using nuke, for example)
      - prometheus:/prometheus
      - grafana:/var/lib/grafana

volumes:
  grafana:
  prometheus:
  kafka:
  zookeeper:

mzworkflows:

  demo:
    steps:
    - step: workflow
      workflow: bring-up-source-data-mysql
    - step: start-services
      services: [dashboard, metabase]
  
  # Brings up everything to run chbench unisolated, i.e. local tests.
  bring-up-source-data-mysql:
    steps:
    - step: start-services
      services: [materialized]
    - step: wait-for-tcp
      host: materialized
      port: 6875
    - step: workflow
      workflow: bring-up-mysql-kafka
  
  # Helper workflows

  bring-up-mysql-kafka:
    steps:
    - step: start-services
      services: [kafka, schema-registry, connect, control-center]
    - step: wait-for-tcp
      host: kafka
      port: 9092
    - step: wait-for-tcp
      host: connect
      port: 8083
      timeout_secs: 120
    - step: wait-for-tcp
      host: control-center
      port: 9021
    - step: start-services
      services: [simple-mysql-connector]
    - step: wait-for-tcp
      host: schema-registry
      port: 8081
      dependencies:
        # sometimes kafka comes up for awhile and then crashes, which will always cause
        # schema-registry to fail because there is no kafka cluster
        - host: kafka
          port: 9092
          hint: >-
            If kafka logs that it has an invalid cluster id ensure that all volumes are
            destroyed via 'mzcompose down -v'
```
</details>

So basically a copy from chbench but removing all that I didn't need to be able to understand little by little, in the future I would want to set up also graphana but after checking all is working.
And well after those files I used `./mzcompose run demo` to run it (here I also had problems because I was modifying docker-entrypoint.sh because it was not working and I wasn't sure), but it took me couple runs to see the control center port and try to run it. 

So today I finally saw that in control-center - topic - ps_log - messages I got changes, but then I tried to `./mzcompose run cli`
```
CREATE MATERIALIZED SOURCE IF NOT EXISTS "avro_pg_log3"
FROM KAFKA BROKER 'kafka:9092' TOPIC 'hostame.database.ps_log'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://schema-registry:8081'
ENVELOPE DEBEZIUM
```
being `ENVELOPE DEBEZIUM` the keyword, because yesterday this query without it was not working. With this I saw that I was getting all the data from the production database, but when I tried to check it in metabase was empty, I could use native query to check it but it didn't appear as table when clicked in the database, so I couldn't filter the columns visually as I could do with the example data.
