### ISSUE TITLE
dbt-materialize: support authenticated connections

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#7067]
Currently, we don't support any sort of authenticated connection from dbt to Materialize. We only support the connection parameters outlined in our [sample profiles](https://github.com/MaterializeInc/materialize/blob/main/misc/dbt-materialize/dbt/include/materialize/sample_profiles.yml#L20):
```
dev:      
     type: materialize     
     threads: [1 or more]      
     host: [host - default is localhost]      
     port: [port - default is 6875]      
     user: materialize      
     pass: [dev_password - any value]      
     dbname: [dbname - default is materialize]      
     schema: [dev_schema - default is public]
```

Different types of authentication options were listed in our [community Slack](https://materializecommunity.slack.com/archives/C01GHNWF690/p1620659405020100) (username/password, TLS). I think we should probably prioritize connecting dbt to Materialize using a cert file because that's a blocker for folks who want to [use dbt with Materialize Cloud](https://materialize.com/docs/cloud/quickstart/#create-and-connect-to-a-materialize-cloud-deployment).

This issue is to explore our options! I'll update here.
