### ISSUE TITLE
Using Redpanda as Sink cannot consumer any messages from sink topics

### ISSUE THREAD

**Issue by royroyisroy** [MaterializeInc/materialize#9283]
### What version of Materialize are you using?
```
     mz_version      
---------------------
 v0.9.13 (193001f31)
```

### How did you install Materialize?

* [x] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?
Failed to consume any messages from sink topic when using Redpanda as Sink, 
using the same source and same materialized view with Kafka Sink works well though.

### Is the issue reproducible? If so, please provide reproduction instructions.
1. Redpanda as a source 
```
materialize=> show create source redpanda;
           Source            |                                                         Create Source                                                         
-----------------------------+-------------------------------------------------------------------------------------------------------------------------------
 materialize.public.redpanda | CREATE SOURCE "materialize"."public"."redpanda" FROM KAFKA BROKER 'redpanda:29092' TOPIC 'gateway.wallet-balance' FORMAT TEXT
(1 row)
```
2. Create materialized view
```
materialize=> show create view raw_wallet_balance;
                 View                  |                                                             Create View                                                              
---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------
 materialize.public.raw_wallet_balance | CREATE VIEW "materialize"."public"."raw_wallet_balance" AS SELECT * FROM "materialize"."public"."redpanda" ORDER BY "mz_offset" DESC
(1 row)
```
3. Create RedPanda Sink
```
materialize=> show create sink raw_wallet_balance_sink;
                    Sink                    |                                                                                                Create Sink                                                                                                 
--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 materialize.public.raw_wallet_balance_sink | CREATE SINK "materialize"."public"."raw_wallet_balance_sink" FROM "materialize"."public"."raw_wallet_balance" INTO KAFKA BROKER 'redpanda:29092' TOPIC 'raw_wallet_balance.sink' FORMAT JSON WITH SNAPSHOT
(1 row)
```
4. Create Kafka Sink
```
materialize=> show create sink raw_wallet_balance_sink_kafka; 
                       Sink                       |                                                                                                 Create Sink                                                                                                  
--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 materialize.public.raw_wallet_balance_sink_kafka | CREATE SINK "materialize"."public"."raw_wallet_balance_sink_kafka" FROM "materialize"."public"."raw_wallet_balance" INTO KAFKA BROKER 'kafka:9092' TOPIC 'raw_wallet_balance.sink' FORMAT JSON WITH SNAPSHOT
(1 row)
```

Kafka can successfully consume the sink topic :
```
bash-5.1# kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic raw_wallet_balance.sink-u114-1637575062-17179988347679306044
{"after":{"row":{"mz_offset":5408,"text":"{\"exchange\":\"***\",\"account_id\":\"***\",\"timestamp\":\"2021-11-23T02:29:40.089335Z\",\"coin\":\"AAVE\",\"free\":\"0.8471242\",\"total\":\"0.0\"}"}},"before":null}
{"after":{"row":{"mz_offset":5403,"text":"{\"exchange\":\"***\",\"account_id\":\"***\",\"timestamp\":\"2021-11-23T02:29:40.042095Z\",\"coin\":\"USDC\",\"free\":\"0.0\",\"total\":\"0.0\"}"}},"before":null}
```

Meanwhile RedPanda failed to consume message from the sink topic:
```
redpanda@1072f02fb523:/$ rpk topic consume raw_wallet_balance.sink-u111-1637575062-17179988347679306044 
<empty>
```

Attached `docker-compose.yaml`
```yaml
redpanda:
    command:
      - redpanda
      - start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --set "redpanda.enable_transactions=true"
      - --set "redpanda.enable_idempotence=true"
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    container_name: redpanda-1
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - myapp

  materialized:
    image: materialize/materialized:v0.9.13
    command:
      - --workers
      - '1'
    ports:
      - "6875:6875"
    networks:
      - myapp

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - myapp
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - myapp
```
