### ISSUE TITLE
chbench demo fails with docker-compose v2

### ISSUE THREAD

**Issue by ra-kete** [MaterializeInc/materialize#9670]
### What version of Materialize are you using?

The GitHub main branch, though this is not an issue with materialized but with one of the demos.

### What was the issue?

If you run the demo at `demo/chbench` with `mzcompose`, and you have docker-compose version 2 installed, to command fails with:

```
WARN[0000] The "MZ_CHBENCH_SNAPSHOT_DIR" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_REGION" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "AWS_SESSION_TOKEN" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/snapshot: empty section between colons
Failed! ERROR: services didn't come up cleanly: materialized
```

The error comes from the `aws-cli` service defined in `demo/chbench/mzcompose.yml`:

```
  aws-cli:
    image: amazon/aws-cli:2.1.18
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      # this is the dir that contains all the individual snapshot directories
      - ${MZ_CHBENCH_SNAPSHOT_DIR}:/snapshot
 ```

`aws-cli` is not a dependency of `demo`, which is why there is no error when docker-compose v1 is used. However, docker-compose v2 always validates the whole compose file, and therefore stumbles over the invalid volume definition, see https://github.com/docker/compose/issues/8841.

The chbench demo is mentioned in the [official documentation](https://materialize.com/docs/demos/business-intelligence/), and there is no mention of the docker-compose v2 incompatibility there, so this seems quite important. I'm not sure if docker-compose v2 is already considered stable at the moment, but it surely will be at some point. At the very least, it is already the default in Arch Linux's package repos.

### Is the issue reproducible? If so, please provide reproduction instructions.

To reproduce, make sure you have:
- docker-compose v2 installed
- the env variable `MZ_CHBENCH_SNAPSHOT_DIR` *not* set

Then run:
```
$ cd demo/chbench
$ ./mzcompose run demo
```

### Workaround

To make the demo work, one can simply set the missing env variable to some dummy value, e.g.:
```
$ env MZ_CHBENCH_SNAPSHOT_DIR=NOTSET ./mzcompose run demo 
```
